### ISSUE TITLE
Request: functions to values or names from enum.

### ISSUE THREAD

**Issue by onodera-punpun** [henzeb/enumhancer#5]
The following migration rule does not work because `cases()` returns an array of enum objects rather than an array of strings:

```php
    $table->enum('status', TransactionStatus::cases());
```

`names()` and `values()` functions would be nice in this case, they would return an array with strings.

Example:

```php
    public static function names(): array
    {
        return array_column(self::cases(), 'name');
    }
```

**Comment by henzeb** [comment]
This is already possible with [Subset](https://github.com/henzeb/enumhancer/blob/main/docs/subset.md#names).

```php
$table->enum('status', TransactionStatus::of()->names());
```

be aware though that migrations should reflect the state after this migration ran.

**Comment by onodera-punpun** [comment]
I overlooked that one, seems like a solution!
